# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ipgeobase.gemspec
gemspec

gem "addressable"
gem "nokogiri-happymapper"
gem "rake", "~> 13.0"
gem "rubocop", "~> 1.21"

group :test do
  gem "minitest", "~> 5.0"
  gem "simplecov", require: false
  gem "webmock"
end
